server {
    listen 80;
    server_name 103.76.55.114;

    # Проксирование всех динамических запросов в Gunicorn
    location / {
        proxy_pass         http://django_app;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }

    # Статические файлы (collectstatic -> /app/staticfiles)
    location /static/ {
        alias /app/staticfiles/;
        expires 30d;
        add_header Cache-Control "public";
    }

    # Медиа-файлы
    location /media/ {
        alias /app/media/;
        expires 30d;
        add_header Cache-Control "public";
    }
}